mysite/library/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('authors/', views.authors, name='authors'),
    path('authors/<int:author_id>', views.author, name='author'),
    path('books/', views.BookListView.as_view(), name="books"),
    path('books/<int:pk>', views.BookDetailView.as_view(), name='book'),
    path('search/', views.search, name='search'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name="profile"),
    path('userbooks/', views.UserBookInstanceListView.as_view(), name='userbooks'),
    path('userbooks/<int:pk>', views.UserBookInstanceDetailView.as_view(), name='userbook'),
    path('userbooks/new', views.UserBookInstanceCreateView.as_view(), name='new_instance'),
    path('userbooks/<int:pk>/update', views.UserBookInstanceUpdateView.as_view(), name="update_instance"),
    path('userbooks/<int:pk>/delete', views.UserBookInstanceDeleteView.as_view(), name='delete_instance'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path("library/", include('library.urls')),
    path('', RedirectView.as_view(url='library/', permanent=True)),
    path('tinymce/', include('tinymce.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
] + (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

urlpatterns += i18n_patterns(
    path('', include('library.urls'), name='news'),
    path('', include('django.contrib.auth.urls'), name="auth"),
)

mysite/library/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User
from datetime import date
from tinymce.models import HTMLField
from PIL import Image
from django.utils.translation import gettext_lazy as _
# Create your models here.

class Genre(models.Model):
    name = models.CharField("Pavadinimas", max_length=200, help_text="Įveskite knygos žanrą (pvz. detektyvas)")

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = _('Genre')
        verbose_name_plural = _('Genres')


class Author(models.Model):
    first_name = models.CharField("Vardas", max_length=100)
    last_name = models.CharField("Pavardė", max_length=100)
    # description = models.TextField("Aprašymas", max_length=2000, default="")
    description = HTMLField("Aprašymas")

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def display_books(self):
        books = self.books.all()
        book_names = list(book.title for book in books)
        books_str = ", ".join(book_names)
        return books_str

    display_books.short_description = "Knygos"

    class Meta:
        verbose_name = _('Author')
        verbose_name_plural = _('Authors')
        ordering = ['id']


class Book(models.Model):
    title = models.CharField(_("Title"), max_length=200)
    summary = models.TextField(_("Summary"), max_length=1000, help_text='Trumpas knygos aprašymas')
    isbn = models.CharField("ISBN", max_length=13, help_text='13 Simbolių <a href="https://www.isbn-international.org/content/what-isbn">ISBN kodas</a>')
    author = models.ForeignKey("Author", on_delete=models.SET_NULL, null=True, related_name="books")
    genre = models.ManyToManyField("Genre", help_text='Išrinkite žanrą(us) šiai knygai')
    cover = models.ImageField(_("Cover"), upload_to='covers', null=True)

    def __str__(self):
        return f"{self.author} - {self.title}"

    def display_genre(self):
        genres = self.genre.all()
        genre_names = list(genre.name for genre in genres)
        genres_str = ", ".join(genre_names)
        return genres_str

    display_genre.short_description = "Žanras"

    class Meta:
        verbose_name = _('Book')
        verbose_name_plural = _('Books')
        ordering = ['-id']

class BookInstance(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, help_text='Unikalus UUID knygos kopijai')
    book = models.ForeignKey("Book", on_delete=models.CASCADE, related_name='instances')
    due_back = models.DateField("Bus prieinama", blank=True)
    reader = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (('a', 'Administruojama'), ('p', 'Paimta'), ('g', 'Galima paimti'), ('r', 'Rezervuota'))

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='a', help_text="Statusas")

    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    def __str__(self):
        return f"{self.book} ({self.uuid}) - {self.status} ({self.due_back})"

    class Meta:
        verbose_name = _('Book Instance')
        verbose_name_plural = _('Book Instances')
        ordering = ['-due_back']


class BookReview(models.Model):
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True, blank=True)
    reviewer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    date_created = models.DateTimeField("Data", auto_now_add=True)
    content = models.TextField("Atsiliepimas", max_length=2000)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nuotrauka = models.ImageField(default='default.png', upload_to="profile_pics")

    def __str__(self):
        return f"{self.user.username} profilis"

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        super().save(force_insert, force_update, using, update_fields)
        img = Image.open(self.nuotrauka.path)
        if img.height > 300 or img.width > 300:
            img.thumbnail((300, 300))
            img.save(self.nuotrauka.path)

mysite/library/forms.py
from .models import BookReview, User, Profile, BookInstance
from django import forms


class BookReviewForm(forms.ModelForm):
    class Meta:
        model = BookReview
        fields = ('content', 'book', 'reviewer')
        widgets = {'book': forms.HiddenInput(), 'reviewer': forms.HiddenInput()}


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email']

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['nuotrauka']

class DateInput(forms.DateInput):
    input_type = 'date'

class UserBookInstanceCreateForm(forms.ModelForm):
    class Meta:
        model = BookInstance
        fields = ['book', 'due_back', 'reader']
        widgets = {'reader': forms.HiddenInput(), 'due_back': DateInput()}

mysite/library/views.py
from . forms import BookReviewForm, UserUpdateForm, ProfileUpdateForm, UserBookInstanceCreateForm
from .models import Book, BookInstance, Author
from django.contrib import messages
from django.contrib.auth.forms import User
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import redirect, render, get_object_or_404, reverse
from django.views import generic
from django.views.decorators.csrf import csrf_protect
from django.views.generic import ListView, UpdateView, DeleteView, DetailView, CreateView
from django.views.generic.edit import FormMixin
from django.utils.translation import gettext as _


# Create your views here.

@csrf_protect
def register(request):
    if request.method == "POST":
        # pasiimame reikšmes iš registracijos formos
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']
        # tikriname, ar sutampa slaptažodžiai
        if password == password2:
            # tikriname, ar neužimtas username
            if User.objects.filter(username=username).exists():
                messages.error(request, _('Username %s already exists!') % username)
                # messages.error(request, f"Vartotojo vardas {username} užimtas!")
                return redirect('register')
            else:
                # tikriname, ar nėra tokio pat email
                if User.objects.filter(email=email).exists():
                    messages.error(request, _('Email %s already exists!') % email)
                    # messages.error(request, f'Vartotojas su el. pašto adresu {email} jau užregistruotas!')
                    return redirect('register')
                else:
                    # jeigu viskas tvarkoje, sukuriame naują vartotoją
                    User.objects.create_user(username=username, email=email, password=password)
                    messages.info(request, _('New user %s registered!') % username)
                    # messages.info(request, f'Naujas vartotojas {username} registruotas!')
                    return redirect('login')
        else:
            # messages.error(request, 'Slaptažodžiai nesutampa')
            messages.error(request, _('Passwords do not match!'))
            return redirect('register')
    return render(request, 'registration/register.html')

def index(request):
    # Suskaičiuokime keletą pagrindinių objektų
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()

    # Laisvos knygos (tos, kurios turi statusą 'g')
    num_instances_available = BookInstance.objects.filter(status__exact='g').count()

    # Kiek yra autorių
    num_authors = Author.objects.all().count()

    num_visits = request.session.get('num_visits', 1)
    request.session['num_visits'] = num_visits + 1

    # Perduoti informaciją į šabloną žodyno pavidale:
    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_visits': num_visits,
    }

    return render(request, 'index.html', context=context)


def authors(request):
    paginator = Paginator(Author.objects.all(), 3)
    page_number = request.GET.get('page')
    paged_authors = paginator.get_page(page_number)
    context = {
        'authors': paged_authors,
    }
    return render(request, 'authors.html', context=context)


def author(request, author_id):  # author_id paimamamas is urls.py
    context = {
        'single_author': get_object_or_404(Author, pk=author_id),
    }
    return render(request, 'author.html', context=context)


def search(request):
    query = request.GET.get('query')
    search_results = Book.objects.filter(Q(title__icontains=query) | Q(summary__icontains=query))
    context = {
        'books': search_results,
        'query': query,
    }
    return render(request, 'search.html', context=context)


from django.contrib.auth.decorators import login_required

def profile(request):
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=request.user) # Kvieciam UserUpdateForm, paduodam per parametrus request.POST ir nurodom request user (pasiimam atnaujintus duomenis)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid(): # tikrinam ar formos yra valid
            u_form.save()
            p_form.save()
            messages.success(request, f"Profilis atnaujintas")
            return redirect('profile') # nukreipiam i funkcija ( ne i url)
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form,
    }
    return render(request, 'profile.html', context)


class BookListView(generic.ListView):
    model = Book
    template_name = 'books.html'
    context_object_name = 'books'
    paginate_by = 10


class BookDetailView(generic.DetailView, FormMixin):
    model = Book
    template_name = 'book.html'
    context_object_name = 'book'
    form_class = BookReviewForm

# nurodome, kur atsidursime komentaro sėkmės atveju.
    def get_success_url(self):
        return reverse('book', kwargs={'pk': self.object.id})

    # standartinis post metodo perrašymas, naudojant FormMixin, galite kopijuoti tiesiai į savo projektą.
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.book = self.object
        form.instance.reviewer = self.request.user
        form.save()
        return super(BookDetailView, self).form_valid(form)


class UserBookInstanceListView(ListView, LoginRequiredMixin):
    model = BookInstance
    template_name = 'user_books.html'
    context_object_name = 'instances'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(reader=self.request.user)

class UserBookInstanceDetailView(generic.DetailView, LoginRequiredMixin):
    model = BookInstance
    template_name = 'user_book.html'
    context_object_name = 'instance'

class UserBookInstanceCreateView(generic.CreateView, LoginRequiredMixin):
        model = BookInstance
        # fields = ['book', 'due_back']
        success_url = '/library/userbooks/' # Patvirtinus forma, nukreipiama i url
        template_name = 'userbook_form.html'
        form_class = UserBookInstanceCreateForm

        def form_valid(self, form):
            form.instance.reader = self.request.user # Nustatom reader ir pasiimam aktyvu useri
            form.instance.status = 'p'
            form.save()
            return super().form_valid(form)

class UserBookInstanceUpdateView(generic.UpdateView, LoginRequiredMixin, UserPassesTestMixin):
    model = BookInstance
    # fields = ['book', 'due_back']
    form_class = UserBookInstanceCreateForm
    success_url = '/library/userbooks/'
    template_name = 'userbook_form.html'

    def form_valid(self, form):
        form.instance.reader = self.request.user
        form.save()
        return super().form_valid(form)

    def test_func(self):
        book_instance = self.get_object()
        return book_instance.reader == self.request.user

class UserBookInstanceDeleteView(DeleteView, LoginRequiredMixin, UserPassesTestMixin):
    model = BookInstance
    success_url = '/library/userbooks/'
    template_name = 'userbook_delete.html'
    context_object_name = 'instance'

    def test_func(self):
        book_instance = self.get_object()
        return book_instance.reader == self.request.user

mysite/library/templates/author.html
{% extends "base.html" %}

{% block title %}Autorius{% endblock %}

{% block content %}
<h1>Autorius</h1>
<p>Vardas: <strong>{{ single_author.first_name }}</strong></p>
<p>Pavarde: <strong>{{ single_author.last_name }}</strong></p>
<p>Aprasymas: {{ single_author.description | safe }}</p>

<h5>Autoriaus knygos: </h5>
<ul>
{% for book in single_author.books.all %}
    <li>{{ book }}</li>
{% endfor %}
</ul>
{% endblock %}

mysite/library/templates/authors.html
{% extends "base.html" %}

{% block title %}Autoriai{% endblock %}

{% block content %}
  <h1>Autoriai</h1>
  <p>Mūsų knygų autorių sąrašas.</p>
<ul>
  {% for author in authors %}
<li><a href="{% url 'author' author.id %}">{{author.first_name}} {{author.last_name}}</a></li>
    {% endfor %}
</ul>
<div class="container puslapiai">
    <nav aria-label="...">
        {% if authors.has_other_pages %}
            <ul class="pagination pagination-sm justify-content-end">
                {% for i in authors.paginator.page_range %}
                    {% if authors.number == i %}
                        <li class="page-item active">
                            <a class="page-link">{{ i }}</a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        {% endif %}
    </nav>
</div>
{% endblock %}

mysite/library/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block title %}{% endblock %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>

{% include 'navbar.html' %}

<div class="jumbotron text-center">
  <h1>Biblioteka</h1>
  <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="currentColor" class="bi bi-book-half" viewBox="0 0 16 16">
  <path d="M8.5 2.687c.654-.689 1.782-.886 3.112-.752 1.234.124 2.503.523 3.388.893v9.923c-.918-.35-2.107-.692-3.287-.81-1.094-.111-2.278-.039-3.213.492V2.687zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783z"/>
</svg>
  <p>Čia yra mano bibliotekos svetaine</p>
</div>

<div class="container">
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{% if message.tags == 'error' %}danger{% elif message.tags == 'info' %}success{% endif %}" role="alert">
                {{ message }}
        </div>
    {% endfor %}
{% endif %}
{% block content %}{% endblock %}
</div>

</body>
</html>

mysite/library/templates/book.html
{% extends "base.html" %}

{% block title %}Knyga{% endblock %}

{% block content %}
{% load static %}
{% load i18n %}
{% if book.cover %}
<img src="{{ book.cover.url }}" style="width:300px" class="card-img-top" alt="...">
{% else %}
<img src="{% static 'img/no-image.png' %}" style="width:300px" class="card-img-top">
{% endif %}
<h1>Knyga:</h1>
<p>Pavadinimas: <strong> {{ book.title }} </strong></p>
<p>Autorius: <strong> {{ book.author }} </strong></p>
<p>ISBN: <strong> {{ book.isbn }} </strong></p>
<p>Žanras: <strong> {{ book.display_genre }} </strong></p>
<p>Aprašymas: {{ book.summary }} </p>
<h5>Knygos egzemplioriai:</h5>
<ul>
    {% for instance in book.instances.all %}
        <li class="{% if instance.status == 'g' %}text-success{% elif instance.status == 'p' %}text-danger{% else %}text-warning{% endif %}">{{ instance.uuid }}, {{ instance.get_status_display }} ({{ instance.due_back }})</li>
    {% endfor %}
</ul>
<br>
<h5>Atsiliepimai:</h5>
  {% if user.is_authenticated %}
    <div class="fieldWrapper">
        <hr><br/>
        <form method="post">
            {% csrf_token %}
            {{ form.content }}
            <input type="submit" value="Pateikti">
        </form>
    </div>
  {% endif %}
{% if book.bookreview_set.all %}
 {% for review in book.bookreview_set.all %}
    <hr>
    <strong>{{ review.reviewer }}</strong>, <em>{{ review.date_created }}</em>
      <p>{{ review.content }}</p>
    {% endfor %}
{% endif %}
{% endblock %}

mysite/library/templates/books.html
{% extends "base.html" %}

{% block title %}Autoriai{% endblock %}

{% block content %}
{% load static %}

<h1>Knygos</h1>
<p>Mūsų knygų sąrašas.</p>

{% if books %}
    <div class="row">
    {% for book in books %}
        <div class="col-md-4 d-flex align-items-stretch">
            <div class="card mb-4 shadow-sm">
                {% if book.cover %}
                <img src="{{ book.cover.url }}" class="card-img-top" style="width:200px" alt="...">
                {% else %}
                <img src="{% static 'img/no-image.png' %}" style="width:200px" class="card-img-top" alt="...">
                {% endif %}
                <div class="card-body">
                   <h6 class="card-subtitle mb-2 text-muted">{{ book.author }}</h6>
                    <p class="card-text"><a href="{{ book.pk }}"> {{ book }}</a></p>
            </div>
        </div>
    </div>
{% endfor %}
</div>
{% else %}
<p>Bibliotekoje knygų nėra.</p>
{% endif %}
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; pirmas</a>
            <a href="?page={{ page_obj.previous_page_number }}">atgal</a>
        {% endif %}

        <span class="current">
            {{ page_obj.number }} iš {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">pirmyn</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">paskutinis &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

mysite/library/templates/index.html
{% extends "base.html" %}

{% block title %}Sveiki atvykę{% endblock %}

{% block content %}
{% load i18n %}
  <h1>{% trans "Local library" %}</h1>
  <p>{% trans "Welcome to my Library" %}</p>
  <p>{% trans "Today we have:" %}</p>
<ul>
    <li><strong>{% trans "Books" %}:</strong> {{ num_book }}</li>
    <li><strong>{% trans "Book Instances" %}:</strong> {{ num_instances }}</li>
    <li><strong>{% trans "Now Available" %}:</strong> {{ num_instances_available }}</li>
    <li><strong>{% trans "Authors" %}:</strong> {{ num_authors }}</li>
</ul>
<p>{% trans "Your visits" %}: {{ num_visits }}</p>
{% endblock content %}

mysite/library/templates/navbar.html
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light bg-light static-top mb-5 shadow">
  <div class="container">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'authors' %}">Autoriai</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'books' %}">Knygos</a>
        </li>
        <li>
          <form action="{% url 'search' %}" class="form-inline my-2 my-md-0">
              <input name="query" class="form-control" type="text" placeholder="Paieška">
          </form>
        </li>
      {% if user.is_authenticated %}
        <li class="nav-item"><a class="nav-link" href="#">
              <svg class="bi bi-person" width="1.5em" height="1.5em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M13 14s1 0 1-1-1-4-6-4-6 3-6 4 1 1 1 1h10zm-9.995-.944v-.002.002zM3.022 13h9.956a.274.274 0 00.014-.002l.008-.002c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664a1.05 1.05 0 00.022.004zm9.974.056v-.002.002zM8 7a2 2 0 100-4 2 2 0 000 4zm3-2a3 3 0 11-6 0 3 3 0 016 0z" clip-rule="evenodd"/>
              </svg>
        {{ user.get_username }}</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'logout'%}?next=/library">Atsijungti</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'userbooks'%}">Mano knygos</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'profile' %}">Mano profilis</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'new_instance' %}">Naujas egzempliorius</a></li>
      {% else %}
        <li class="nav-item"><a class="nav-link" href="{% url 'login'%}?next={{request.path}}">Prisijungti</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'register' %}">Registruotis</a></li>
      </ul>
      {% load i18n %}
      <form action="{% url 'set_language' %}" method="post">
        {% csrf_token %}
        <input name="next" type="hidden" value="{{ redirect_to }}"/>
        <select name="language" onchange="this.form.submit()">
          {% load static %}
          {% get_current_language as LANGUAGE_CODE %}
          {% get_available_languages as LANGUAGES %}
          {% for lang in LANGUAGES %}
          <option style="background-image: url({% static 'img/lt.png' %});" value="{{ lang.0 }}" {% if lang.0 == LANGUAGE_CODE %} selected="selected" hreflang="{{ lang.0 }}"{% endif %}>
            {{ lang.1 }}
          </option>
          {% endfor %}
        </select>
      </form>
      {% endif %}
    </div>
  </div>
</nav>

mysite/library/templates/profile.html
{% extends "base.html" %}

{% block title %}profile.html puslapis{% endblock %}

{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.nuotrauka.url }}">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>
      <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% load crispy_forms_tags %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Profilio info</legend>
                {{ u_form|crispy }}
                {{ p_form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Atnaujinti</button>
            </div>
        </form>
    </div>
{% endblock content %}

mysite/library/templates/search.html
{% extends "base.html" %}

{% block title %}Search.html puslapis{% endblock %}

{% block content %}
  <h2>Paieškos pagal "{{query}}" rezultatai:</h2>
  </br>
  {% if books %}
  <ul>
    {% for book in books %}
      <li>
        <a href="{% url 'book' book.pk %}">{{ book.title }}</a> ({{book.author}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>Oops. Nieko neradome :(</p>
  {% endif %}

  {% endblock %}

mysite/library/templates/user_book.html
{% extends "base.html" %}

{% block title %}Mano knyga{% endblock %}

{% block content %}
<h1>Mano paimta knyga:</h1>
<hr>
    <img src="{{ instance.book.cover.url }}">
    <br>
    <br>
    <p><strong class="{% if instance.is_overdue %}text-danger{% endif %}">Pavadinimas: {{instance.book.title}} ({{ instance.due_back }}) </strong></p>
    <p><strong >UUID: {{ instance.uuid }} </strong></p>
    <p><strong >Statusas: {{ instance.get_status_display }} </strong></p>
    {% if object.reader == user %}
        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'update_instance' instance.id %}">Redaguoti</a>
        <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'delete_instance' instance.id %}">Ištrinti</a>
    {% endif %}
{% endblock %}

mysite/library/templates/user_books.html
{% extends "base.html" %}

{% block title %}Mano knygos{% endblock %}

{% block content %}

<h1>Mano knygos</h1>
{% if instances %}
<ul>
{% for book in instances %}
    <a href="{{ book.id }}">
        <li class="{% if book.is_overdue %}text-danger{% endif %}">{{ book }}</li>
    </a>
{% endfor %}
</ul>
{% else %}
<p>Šiuo metu nesate paėmę knygų.</p>
{% endif %}
{% endblock %}